"""update_tablessssss

Revision ID: 032fc2fb988e
Revises: a033a4f26741
Create Date: 2025-10-05 19:29:12.331081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032fc2fb988e'
down_revision = 'a033a4f26741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organized_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('challenge_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'challenges', ['challenge_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organized_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('challenge_id')

    # ### end Alembic commands ###
