"""update_table

Revision ID: 274c857b1bb6
Revises: ec1ab9fed5ef
Create Date: 2025-10-05 15:36:55.558466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274c857b1bb6'
down_revision = 'ec1ab9fed5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organized_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['organized_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_participants_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_participants_id'], ['event_participants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_participants_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_users')
    op.drop_table('event_participants')
    op.drop_table('organized_events')
    # ### end Alembic commands ###
