"""updatess

Revision ID: 33f560e352ae
Revises: 081895766dd6
Create Date: 2025-10-01 20:03:32.613282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33f560e352ae'
down_revision = '081895766dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
