"""update_tables

Revision ID: 94b19d815671
Revises: 274c857b1bb6
Create Date: 2025-10-05 15:39:45.306125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94b19d815671'
down_revision = '274c857b1bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_participant_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('event_users_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'event_participants', ['event_participant_id'], ['id'])
        batch_op.drop_column('event_participants_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_participants_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_users_ibfk_1'), 'event_participants', ['event_participants_id'], ['id'])
        batch_op.drop_column('event_participant_id')

    # ### end Alembic commands ###
