"""update profile

Revision ID: 950696e2d045
Revises: eca6f4af503a
Create Date: 2025-09-29 14:37:12.971376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950696e2d045'
down_revision = 'eca6f4af503a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
