"""update_tabless

Revision ID: a033a4f26741
Revises: 94b19d815671
Create Date: 2025-10-05 15:52:43.708449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a033a4f26741'
down_revision = '94b19d815671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_users')
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('organized_event_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('event_participants_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'organized_events', ['organized_event_id'], ['id'])
        batch_op.drop_column('id')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_participants_ibfk_1'), 'organized_events', ['event_id'], ['id'])
        batch_op.drop_column('organized_event_id')
        batch_op.drop_column('user_id')

    op.create_table('event_users',
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('event_participant_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_participant_id'], ['event_participants.id'], name=op.f('event_users_ibfk_3')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('event_users_ibfk_2')),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
